version: 1.0.{build}
image: Visual Studio 2019
platform: x64

environment:
  COMPILER: msvc2019
  matrix:
    # Interleave PYTHON, ARCH and GEOS_VERSION
#    - PYTHON: "C:\\Python35-x64"
#      ARCH: x64
#      GEOS_VERSION: "3.5.2"
    - PYTHON: "C:\\Python36"
      ARCH: x86
      GEOS_VERSION: "3.6.4"
#    - PYTHON: "C:\\Python37-x64"
#      ARCH: x64
#      GEOS_VERSION: "3.7.3"
#    - PYTHON: "C:\\Python38"
#      ARCH: x86
#      GEOS_VERSION: "3.8.1"
#    - PYTHON: "C:\\Python39-x64"
#      ARCH: x64
#      GEOS_VERSION: "3.8.1"

init:
- cmd: >-
    SET PATH=c:\python36;c:\python36\Scripts;C:\Program Files\Git\cmd;C:\Program Files (x86)\7-Zip\;C:\Program Files\Git\usr\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\
    cd FastVoxel
    mkdir build
    cd build

build_script:
- cmake ..
- make

artifacts:
- path: build\exe.win32-3.6\
